### ISSUE TITLE
Media Types

### ISSUE THREAD

**Issue by SamDrummond** [Esri/storymap-cascade#5]
I'm interested in building a custom media type... another option for adding a custom chart control in an immersive section. Am I able to do this. Do you have documentation for this?

**Comment by skitterm** [comment]
Hi Sam,

Glad to hear you're interested in customizing Cascade! We don't have any documentation for adding a custom media type (our docs mainly describe how to download and self-host the application). Adding a new media type is possible, but fairly complex. The media types extend a common base class, but they often have their own behavior. What's more, these media types often act differently depending on where they are in the story (in the cover, in an immersive section background, or a narrative section block).

Off the top of my head, at minimum you would need to:
1) Add a class for the new media item (like [this](https://github.com/Esri/storymap-cascade/blob/master/src/app/storymaps/tpl/view/media/WebPage.jsx))
2) Give it a handlebars template for the immersive section background (like [this](https://github.com/Esri/storymap-cascade/blob/master/src/app/storymaps/tpl/view/media/WebPageBackground.hbs))
3) Add it to the "add media" menu 

You can see how the pattern works with the webpage media type in these links. For the webpage.jsx code itself, `render` injects the handlebars template with the data, and `postCreate` is called after that template is in the DOM (so any DOM manipulation/3rd-party library code can go there).

If you can get away with adding the chart control to your Cascade as a webpage (instead of coding up a new media type), I'd do that. You could even have the Cascade app and the webpage "talk" to each other if you needed events.

**Comment by SamDrummond** [comment]
Thanks so much @skitterm.  Sorry this has taken me so long to reply.  It will be a little longer before I get a chance to try your advice but will keep you in the loop on my progress.

**Comment by skitterm** [comment]
@SamDrummond I'm going to close this ticket; let us know if you run into any further issues.
