### ISSUE TITLE
Autoplay settings

### ISSUE THREAD

**Issue by richardalain83** [Esri/storymap-cascade#7]
Hi, 
I know this issue is not directly related to the storymap-cascade but i can't find any information on how to setup the default timeout for the autoplay.
If I append the &autoplay=1 in the url, my project is loading with autoplay but default to 10 sec. I would like to have a default of 5 sec.

Is it possible to change the default timeout in JS once loaded?

Thanks

**Comment by skitterm** [comment]
Hi Richard,
Our apps don't allow changing the default autoplay time interval out of the box. If you're using the source (unminified) code, though, you can change it. In `Autoplay.jsx`, you can change the `DEFAULT_DELAY` value to be `5` instead of `10`, as shown [here](https://github.com/Esri/storymap-cascade/blob/master/src/app/storymaps/tpl/view/ui/Autoplay.jsx#L10). 

If you're feeling adventurous, you can hook up a URL parameter to that default value by passing it in the `new Autoplay()` constructor ([here](https://github.com/Esri/storymap-cascade/blob/master/src/app/storymaps/tpl/core/MainView.js#L575)) and wiring it up in `Autoplay.jsx`.

Of course, the viewer of the story can currently change the time interval via the autoplay slider at the bottom of the screen, but I'm assuming you're talking about applying a new default value.

**Comment by skitterm** [comment]
@richardalain83 I'll close this issue; feel free to reach out if your question was not resolved.
